/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FundsReceiver } from "./FundsReceiver";
export type { OwnableSkeleton } from "./OwnableSkeleton";
export type { PublicMulticall } from "./PublicMulticall";
