/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DropConfigGetter } from "./DropConfigGetter";
export type { EditionMetadataRenderer } from "./EditionMetadataRenderer";
