/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PublicMulticall,
  PublicMulticallInterface,
} from "../../../src/utils/PublicMulticall";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class PublicMulticall__factory {
  static readonly abi = _abi;
  static createInterface(): PublicMulticallInterface {
    return new utils.Interface(_abi) as PublicMulticallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PublicMulticall {
    return new Contract(address, _abi, signerOrProvider) as PublicMulticall;
  }
}
