/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as editionMetadataRendererSol from "./EditionMetadataRenderer.sol";
export type { editionMetadataRendererSol };
export type { DropMetadataRenderer } from "./DropMetadataRenderer";
export type { MetadataRenderAdminCheck } from "./MetadataRenderAdminCheck";
