/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IERC721Drop {
  export type SalesConfigurationStruct = {
    publicSalePrice: PromiseOrValue<BigNumberish>;
    maxSalePurchasePerAddress: PromiseOrValue<BigNumberish>;
    publicSaleStart: PromiseOrValue<BigNumberish>;
    publicSaleEnd: PromiseOrValue<BigNumberish>;
    presaleStart: PromiseOrValue<BigNumberish>;
    presaleEnd: PromiseOrValue<BigNumberish>;
    presaleMerkleRoot: PromiseOrValue<BytesLike>;
  };

  export type SalesConfigurationStructOutput = [
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    publicSalePrice: BigNumber;
    maxSalePurchasePerAddress: number;
    publicSaleStart: BigNumber;
    publicSaleEnd: BigNumber;
    presaleStart: BigNumber;
    presaleEnd: BigNumber;
    presaleMerkleRoot: string;
  };
}

export interface NFTCreatorV1Interface extends utils.Interface {
  functions: {
    "createAndConfigureDrop(string,string,address,uint64,uint16,address,bytes[],address,bytes)": FunctionFragment;
    "createDrop(string,string,address,uint64,uint16,address,(uint104,uint32,uint64,uint64,uint64,uint64,bytes32),string,string)": FunctionFragment;
    "createEdition(string,string,address,uint64,uint16,address,(uint104,uint32,uint64,uint64,uint64,uint64,bytes32),string,string,string)": FunctionFragment;
    "dropMetadataRenderer()": FunctionFragment;
    "editionMetadataRenderer()": FunctionFragment;
    "mintFee()": FunctionFragment;
    "mintFeeRecipient()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setMintFee(uint256)": FunctionFragment;
    "setmintFeeRecipient(address)": FunctionFragment;
    "setupDropsContract(string,string,address,address,uint64,uint16,(uint104,uint32,uint64,uint64,uint64,uint64,bytes32),address,bytes)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createAndConfigureDrop"
      | "createDrop"
      | "createEdition"
      | "dropMetadataRenderer"
      | "editionMetadataRenderer"
      | "mintFee"
      | "mintFeeRecipient"
      | "owner"
      | "renounceOwnership"
      | "setMintFee"
      | "setmintFeeRecipient"
      | "setupDropsContract"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createAndConfigureDrop",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createDrop",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      IERC721Drop.SalesConfigurationStruct,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createEdition",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      IERC721Drop.SalesConfigurationStruct,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dropMetadataRenderer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "editionMetadataRenderer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mintFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMintFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setmintFeeRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setupDropsContract",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      IERC721Drop.SalesConfigurationStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAndConfigureDrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDrop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEdition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropMetadataRenderer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editionMetadataRenderer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMintFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setmintFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupDropsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "CreatedDrop(address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedDrop"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface CreatedDropEventObject {
  creator: string;
  editionContractAddress: string;
  editionSize: BigNumber;
}
export type CreatedDropEvent = TypedEvent<
  [string, string, BigNumber],
  CreatedDropEventObject
>;

export type CreatedDropEventFilter = TypedEventFilter<CreatedDropEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface NFTCreatorV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTCreatorV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createAndConfigureDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      setupCalls: PromiseOrValue<BytesLike>[],
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataURIBase: PromiseOrValue<string>,
      metadataContractURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createEdition(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      description: PromiseOrValue<string>,
      animationURI: PromiseOrValue<string>,
      imageURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    dropMetadataRenderer(overrides?: CallOverrides): Promise<[string]>;

    editionMetadataRenderer(overrides?: CallOverrides): Promise<[string]>;

    mintFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMintFee(
      _mintFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setmintFeeRecipient(
      _mintFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setupDropsContract(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      fundsRecipient: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createAndConfigureDrop(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    defaultAdmin: PromiseOrValue<string>,
    editionSize: PromiseOrValue<BigNumberish>,
    royaltyBPS: PromiseOrValue<BigNumberish>,
    fundsRecipient: PromiseOrValue<string>,
    setupCalls: PromiseOrValue<BytesLike>[],
    metadataRenderer: PromiseOrValue<string>,
    metadataInitializer: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createDrop(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    defaultAdmin: PromiseOrValue<string>,
    editionSize: PromiseOrValue<BigNumberish>,
    royaltyBPS: PromiseOrValue<BigNumberish>,
    fundsRecipient: PromiseOrValue<string>,
    saleConfig: IERC721Drop.SalesConfigurationStruct,
    metadataURIBase: PromiseOrValue<string>,
    metadataContractURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createEdition(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    defaultAdmin: PromiseOrValue<string>,
    editionSize: PromiseOrValue<BigNumberish>,
    royaltyBPS: PromiseOrValue<BigNumberish>,
    fundsRecipient: PromiseOrValue<string>,
    saleConfig: IERC721Drop.SalesConfigurationStruct,
    description: PromiseOrValue<string>,
    animationURI: PromiseOrValue<string>,
    imageURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  dropMetadataRenderer(overrides?: CallOverrides): Promise<string>;

  editionMetadataRenderer(overrides?: CallOverrides): Promise<string>;

  mintFee(overrides?: CallOverrides): Promise<BigNumber>;

  mintFeeRecipient(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMintFee(
    _mintFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setmintFeeRecipient(
    _mintFeeRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setupDropsContract(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    defaultAdmin: PromiseOrValue<string>,
    fundsRecipient: PromiseOrValue<string>,
    editionSize: PromiseOrValue<BigNumberish>,
    royaltyBPS: PromiseOrValue<BigNumberish>,
    saleConfig: IERC721Drop.SalesConfigurationStruct,
    metadataRenderer: PromiseOrValue<string>,
    metadataInitializer: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createAndConfigureDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      setupCalls: PromiseOrValue<BytesLike>[],
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    createDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataURIBase: PromiseOrValue<string>,
      metadataContractURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    createEdition(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      description: PromiseOrValue<string>,
      animationURI: PromiseOrValue<string>,
      imageURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    dropMetadataRenderer(overrides?: CallOverrides): Promise<string>;

    editionMetadataRenderer(overrides?: CallOverrides): Promise<string>;

    mintFee(overrides?: CallOverrides): Promise<BigNumber>;

    mintFeeRecipient(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setMintFee(
      _mintFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setmintFeeRecipient(
      _mintFeeRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setupDropsContract(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      fundsRecipient: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CreatedDrop(address,address,uint256)"(
      creator?: PromiseOrValue<string> | null,
      editionContractAddress?: PromiseOrValue<string> | null,
      editionSize?: null
    ): CreatedDropEventFilter;
    CreatedDrop(
      creator?: PromiseOrValue<string> | null,
      editionContractAddress?: PromiseOrValue<string> | null,
      editionSize?: null
    ): CreatedDropEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    createAndConfigureDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      setupCalls: PromiseOrValue<BytesLike>[],
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataURIBase: PromiseOrValue<string>,
      metadataContractURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createEdition(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      description: PromiseOrValue<string>,
      animationURI: PromiseOrValue<string>,
      imageURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    dropMetadataRenderer(overrides?: CallOverrides): Promise<BigNumber>;

    editionMetadataRenderer(overrides?: CallOverrides): Promise<BigNumber>;

    mintFee(overrides?: CallOverrides): Promise<BigNumber>;

    mintFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMintFee(
      _mintFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setmintFeeRecipient(
      _mintFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setupDropsContract(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      fundsRecipient: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createAndConfigureDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      setupCalls: PromiseOrValue<BytesLike>[],
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createDrop(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataURIBase: PromiseOrValue<string>,
      metadataContractURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createEdition(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      fundsRecipient: PromiseOrValue<string>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      description: PromiseOrValue<string>,
      animationURI: PromiseOrValue<string>,
      imageURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    dropMetadataRenderer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    editionMetadataRenderer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintFeeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMintFee(
      _mintFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setmintFeeRecipient(
      _mintFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setupDropsContract(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      defaultAdmin: PromiseOrValue<string>,
      fundsRecipient: PromiseOrValue<string>,
      editionSize: PromiseOrValue<BigNumberish>,
      royaltyBPS: PromiseOrValue<BigNumberish>,
      saleConfig: IERC721Drop.SalesConfigurationStruct,
      metadataRenderer: PromiseOrValue<string>,
      metadataInitializer: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
